language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-drupal' ]; then cd .. && eval "mv $currentfolder generator-drupal" && cd generator-drupal; fi

